### ISSUE TITLE
HACS Integration fails parsing the blinds

### ISSUE THREAD

**Issue by Nippey** [StephanU/PyMyGekko#6]
Hello Stephan,

thank you for this integration.
I just stumbled over it and had to try it out via HACS :)
(Running Version 0.028)

Maybe my Slide2 does something differently, but it got stuck parsing my blinds:
(Running Version 6800-14)

```
2023-11-15 14:39:04.684 ERROR (MainThread) [PyMyGekko.DataProvider] Json Parsing the response failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/PyMyGekko/DataProvider.py", line 114, in read_data
    self.status = json.loads(responseText)
    ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/PyMyGekko/DataProvider.py", line 45, in status
    subscriber.update_status(self._status)
  File "/usr/local/lib/python3.11/site-packages/PyMyGekko/resources/Blinds.py", line 72, in update_status
    (
ValueError: too many values to unpack (expected 5)
```
This is just the first of multiple traces, I will append the whole log as file.

This is my API Description:
```
	"blinds":	{
		"item0":	{
			"name":	"Küche - Fenster",
			"page":	"EG",
			"sumstate":	{
				"description":	"Summary of the states and their formats",
				"format":	"currentState enum[-2=holdDown,-1=movingDown,0=stop,1=movingUp,2=holdUp](); positionLevel float[0.00,100.00](%); rotationLevel float[0.00,100.00](%); elementInfo enum[0=ok,1=manualOff,2=manualOn,3=locked,4=alarm](); rotationRange enum[90=ninety,180=hundredEighty](°); ",
				"type":	"STRING",
				"permission":	"READ"
			},
			"scmd":	{
				"description":	"Summary of the commands and their formats",
				"format":	"-2|-1|0|1|2|T|P55.4|S32.4 (Hold_down|Down|Stop|Up|Hold_up|Toggle|Position|Angle)",
				"type":	"STRING",
				"permission":	"WRITE",
				"index":	150070
			}
		},
```

And this is my API status:
```
	"blinds":	{
		"item0":	{
			"sumstate":	{
				"value":	"0;0.00;;0;90;"
			}
		},
```

It looks to me, like the trailing semicolon is also split by your code:
https://github.com/StephanU/PyMyGekko/blob/d264ecee4220bc9422e83b236b947bb383fe837c/PyMyGekko/resources/Blinds.py#L78
So, it actually tries to fit a 6-element list into 5 entries ...

Best Regards
Matthias

**Comment by Nippey** [comment]
[home-assistant_mygekko_2023-11-15T13-41-11.227Z.log](https://github.com/StephanU/PyMyGekko/files/13365711/home-assistant_mygekko_2023-11-15T13-41-11.227Z.log)

**Comment by Nippey** [comment]
If you think this is robust enough, one could just do a hard cut ...
`.split(";")[0:4]`

**Comment by StephanU** [comment]
Hi Matthias,
you happened to have downloaded an intermediate development state I was using to test the integration with a newer version of MyGekko.
I initially developed/tested this library and the HA integration with a MyGekko Slide 2 (Version 596610) of a friend (I don't own a MyGekko myself). I now learned that for newer version the data format differs in the API status result.
```
"blinds":	{
  "item0": {
    "sumstate": {
      "value": "0;0.00;;0;90;"
    }
},
```
In your example: The trailing ";" in the value property does not exist in "Version 596610", which results in the error you mentioned `"ValueError: too many values to unpack (expected 5)"`.

With the help of google I solved it this way: https://github.com/StephanU/PyMyGekko/blob/dev/PyMyGekko/resources/Blinds.py#L79

So, with version 0.0.29 of the integration it should work for the older and the newer version of MyGekko.

**Comment by StephanU** [comment]
I'm not fluent in Python... is the solution you proposed `.split(";")[0:4]` in some way better than the `*other` approach? :)

**Comment by Nippey** [comment]
I am also working my way into more complex python right now.
But especially HA always scared me :D

I like your solution. Didn't know you could unpack the remainder in a single variable using the asterisk.

I think you inherently answered another question I didn't even ask yet:
You use the PLUS API just because you are developing remote, right?
I would prefer the local API.
If you don't mind, maybe I can extend your code to support both APIs.

But I might take some time, our family will grow within the next days ;)

Grüße aus NRW/Dinslaken

**Comment by Nippey** [comment]
Awesome, Integration 0.0.29 is running now!

**Comment by StephanU** [comment]
Thanks for closing the issue :) 
Any help developing the integration is appreciated!
Just mail me and we can chat about it. 
Until then, all the best for your new arrival :)

**Comment by Nippey** [comment]
Thanks for the wishes! All is wonderful :)

Wow, just found time again to update HA and found your integration is working more than fine!
I don't plan my time that much in advance, but if you need a beta tester, I' be happy to stress your code a bit.
For now, I am more interested in features not exported by the api: "Sonnenschutz".

I am hesitant, if I want to outsource the control to HA :D
